packages/mottai_flutter_app/ios/Podfile, packages/mottai_flutter_app/ios/Podfile.lock, packages/mottai_flutter_app/ios/Runner.xcodeproj/project.pbxproj, packages/mottai_flutter_app/ios/Runner.xcworkspace/contents.xcworkspacedata
ビルド時に以下のエラーが発生
`Unable to find a target named "RunnerTests" in project  Runner.xcodeproj`
そのためPodfileのRunnerTests部分をコメントアウトすることでビルドが通った。
参考記事
https://stackoverflow.com/questions/76247185/unable-to-find-a-target-named-runnertests-in-project-runner-xcodeproj
その他ビルド時に生成された差分を含んでいます
=> 最初のビルド時にできた差分

packages/mottai_flutter_app/ios/Runner.xcodeproj/project.pbxproj
=> fix: fix Environment.swift reference path

packages/mottai_flutter_app/ios/Podfile, packages/mottai_flutter_app/ios/Podfile.lock
=> build: update Podfile firestore ios sdk framework tag

packages/dart_flutter_common/lib/dart_flutter_common.dart, packages/dart_flutter_common/lib/src/int.dart, packages/firebase_common/lib/src/firestore_repositories/chat_message.dart, packages/mottai_flutter_app/lib/chat/chat_room.dart, packages/mottai_flutter_app/lib/chat/chat_room_state.dart, packages/mottai_flutter_app/lib/chat/chat_room_state.freezed.dart, packages/mottai_flutter_app/lib/chat/ui/chat_room.dart, packages/mottai_flutter_app/lib/color.dart, packages/mottai_flutter_app/lib/development/development_items/ui/development_items.dart, packages/mottai_flutter_app/pubspec.lock, packages/mottai_flutter_app/pubspec.yaml
@Muhyun-Kim 
ちょっと方針で混乱させてしまったのと、かなり複雑だなということで、無限スクロールのチャットのベースの実装をしました。
ぜひこの PR をチェックアウトして動作確認しながら内容（MVC アーキテクチャに照らし合わせながら）を理解してください。
`host01@example.com` のホストモード, `worker01@example.com` でチャットができます。
良さそうだと思ったら Approve をお願いします！Approve をもらったら main にマージします。
その上で、
- まだ送信者のプロフィール画像が実際のユーザーの画像になっていない
- 既読・未読の実装はされていない
- UI が仮である
という課題が残っているので、この PR の main へのマージ後、それらをぜひムヒョンくんが担当してください！
`chatRoomId` はルーティングの実装を行うときに実際の ID を取れるようにするつもりなので、ハードコードにしています。そのままで構いません。
動作確認もかねて、この PR をチェックアウトして手元で確認してみてください。
=> 無限スクロールのチャットのベースの実装

packages/firebase_common/lib/src/firestore_documents/chat_message.flutterfire_gen.dart, packages/firebase_common/lib/src/firestore_documents/chat_room.flutterfire_gen.dart, packages/firebase_common/lib/src/firestore_documents/fcm_token.flutterfire_gen.dart, packages/firebase_common/lib/src/firestore_documents/force_update_config.flutterfire_gen.dart, packages/firebase_common/lib/src/firestore_documents/host.flutterfire_gen.dart, packages/firebase_common/lib/src/firestore_documents/host_location.flutterfire_gen.dart, packages/firebase_common/lib/src/firestore_documents/in_review_config.flutterfire_gen.dart, packages/firebase_common/lib/src/firestore_documents/job.flutterfire_gen.dart, packages/firebase_common/lib/src/firestore_documents/read_status.flutterfire_gen.dart, packages/firebase_common/lib/src/firestore_documents/sample_todo.flutterfire_gen.dart, packages/firebase_common/lib/src/firestore_documents/worker.flutterfire_gen.dart, packages/firebase_common/pubspec.lock, packages/firebase_common/pubspec.yaml
=> Update flutterfire gen dependency

packages/dart_flutter_common/.gitignore, packages/dart_flutter_common/test/date_time_test.dart
なし
DateTimeExtensionのテストを追加しました 
コミットメッセージ通りです！
=> DateTimeのExtensionのテストを追加

packages/mottai_flutter_app/android/app/src/main/AndroidManifest.xml
Reverts KosukeSaigusa/mottai-flutter-app#74
=> Revert "アンドロイドビルドができない不具合の修正"

packages/mottai_flutter_app/lib/development/sample_todo/ui/sample_todos_controller.dart, packages/mottai_flutter_app/lib/main.dart
=> fix: fix showing dialog bug

.firebaserc
=> chore: add prod Firebase project to .firebaserc

packages/mottai_flutter_app/lib/auth/ui/auth_controller.dart
=> refactor: refacor auth controller sign in method

packages/firebase_common/lib/src/firestore_documents/job.dart, packages/firebase_common/lib/src/firestore_documents/job.flutterfire_gen.dart
=> feat: add title to job document

.github/workflows/analyze_code_pullrequest.yaml, .vscode/settings.json, packages/firebase_common/lib/src/firestore_repositories/chat_room.dart, packages/firebase_common/lib/src/firestore_repositories/fcm_token.dart, packages/firebase_common/lib/src/firestore_repositories/host_location.dart, packages/firebase_common/lib/src/firestore_repositories/in_review_config.dart, packages/firebase_common/lib/src/firestore_repositories/read_status.dart, packages/mottai_flutter_app/lib/development/development_items/ui/development_items.dart
=> #91 Github Actionsにflutter analyzeを追加

.github/workflows/flutter_test.yaml, melos.yaml, packages/firebase_common/test/tmp_test.dart
=> github actionsのCIを追加

packages/dart_flutter_common/lib/dart_flutter_common.dart, packages/dart_flutter_common/lib/src/widgets/web_link.dart, packages/dart_flutter_common/pubspec.lock, packages/dart_flutter_common/pubspec.yaml, packages/mottai_flutter_app/android/app/src/main/AndroidManifest.xml, packages/mottai_flutter_app/ios/Runner/Info.plist, packages/mottai_flutter_app/lib/development/development_items/ui/development_items.dart, packages/mottai_flutter_app/lib/development/web_link/web_link_stub.dart, packages/mottai_flutter_app/pubspec.lock
- #67
close #67
URLリンクのウィジェットを作成しました。
パッケージは[flutter_linkify](https://pub.dev/packages/flutter_linkify)を使用しており、
ブラウザへの遷移のために[url_launcher](https://pub.dev/packages/url_launcher)も使用しています。
なし
=> #67 URLリンクウィジェットの作成

functions/.prettierrc, functions/src/callable-functions/createFirebaseAuthCustomToken.ts, functions/src/firebase-documents/worker.flutterfireGen.ts, functions/src/types/line.d.ts
=> Ts document model sample

packages/firebase_common/lib/src/firestore_repositories/chat_message.dart, packages/firebase_common/lib/src/firestore_repositories/chat_room.dart, packages/mottai_flutter_app/ios/Podfile.lock, packages/mottai_flutter_app/lib/chat/chat_rooms.dart, packages/mottai_flutter_app/lib/chat/read_status.dart, packages/mottai_flutter_app/lib/chat/ui/chat_room.dart, packages/mottai_flutter_app/lib/chat/ui/chat_rooms.dart
close #43 
- 未読メッセージ数の取得とチャットルーム一覧上のアイテムへの表示
- 最新メッセージの取得とチャットルーム一覧上のアイテムへの表示
- 最新メッセージの送信日取得とチャットルーム一覧上のアイテムへの表示
- 送信者名の取得とチャットルーム一覧上のアイテムへの表示
- 送信者の画像を取得とチャットルーム一覧上のアイテムへの表示
- リストアイテムをListTileにWidgetを分ける
- デザイン調整
->#133 で対応予定
<image src="https://github.com/kosukesaigusa/mottai-flutter-app/assets/25321380/c8b2a04e-5e65-4d9d-ad32-6d9bdbdd507d" width=300/>
なし
=> チャットルーム一覧ページの実装

packages/mottai_flutter_app/lib/chat/chat_rooms.dart
=> fix: fix unread count limit

packages/firebase_common/lib/src/firestore_repositories/chat_room.dart, packages/firebase_common/pubspec.lock, packages/mottai_flutter_app/lib/auth/ui/auth_controller.dart, packages/mottai_flutter_app/lib/chat/chat_room.dart, packages/mottai_flutter_app/lib/chat/chat_rooms.dart, packages/mottai_flutter_app/lib/chat/ui/chat_room.dart, packages/mottai_flutter_app/lib/chat/ui/chat_rooms.dart, packages/mottai_flutter_app/lib/development/development_items/ui/development_items.dart, packages/mottai_flutter_app/lib/development/email_and_password_sign_in/ui/email_and_password_sign_in.dart, packages/mottai_flutter_app/lib/job/ui/job_detail.dart, packages/mottai_flutter_app/lib/job/ui/start_chat_with_host_controller.dart, packages/mottai_flutter_app/lib/map/ui/map.dart, packages/mottai_flutter_app/lib/my_account/ui/my_account.dart, packages/mottai_flutter_app/lib/review/ui/reviews.dart, packages/mottai_flutter_app/lib/root/ui/root.dart, packages/mottai_flutter_app/lib/router/router.dart, packages/mottai_flutter_app/lib/router/router.gr.dart, packages/mottai_flutter_app/pubspec.lock
=> feat: add app base features

packages/mottai_flutter_app/lib/push_notification/firebase_messaging.dart
=> chore: update comment

packages/mottai_flutter_app/lib/host/ui/host.dart, packages/mottai_flutter_app/lib/my_account/ui/my_account.dart, packages/mottai_flutter_app/lib/user/ui/user_mode.dart, packages/mottai_flutter_app/lib/worker/ui/worker.dart
=> feat: show worker or host content on my account page

packages/mottai_flutter_app/lib/development/geoflutterfire_plus/geoflutterfire_plus.dart
=> chore: update geoflutterfire_plus sample codes

functions/src/callable-functions/notificationSlack.ts, functions/src/index.ts
#147
close #147
Slackへ通知を行う関数の作成を行いました。
環境変数を使用して通知をします。
変更なし
なし
=> #147 Slack通知を行う関数の作成

packages/mottai_flutter_app/ios/Podfile.lock
=> chore: update Podfile.lock

packages/mottai_flutter_app/ios/Runner/Info.plist
=> fix: fix line login bug

packages/firebase_common/lib/src/firebase_storage/firebase_storage.dart, packages/mottai_flutter_app/lib/exception.dart, packages/mottai_flutter_app/lib/force_update/force_update.dart, packages/mottai_flutter_app/lib/image/image_picker.dart, packages/mottai_flutter_app/lib/package_info.dart, packages/mottai_flutter_app/test/package_info_test.dart
=> refactor: refactor codes

packages/firebase_common/lib/src/firestore_documents/chat_message.dart, packages/firebase_common/lib/src/firestore_documents/host.dart, packages/firebase_common/lib/src/firestore_documents/host_location.dart, packages/firebase_common/lib/src/firestore_documents/job.dart, packages/firebase_common/pubspec.lock, packages/firebase_common/pubspec.yaml
=> fix: remove flutterfire_gen_ts from firebase_common

packages/mottai_flutter_app/android/.gitignore, packages/mottai_flutter_app/android/app/build.gradle
=> build: add android build related files

packages/firebase_common/lib/src/firestore_documents/review.dart, packages/firebase_common/lib/src/firestore_documents/review.flutterfire_gen.dart
=> feat: add review model

.github/workflows/release_to_dev.yaml, packages/mottai_flutter_app/ios/ExportOptions.plist, packages/mottai_flutter_app/pubspec.yaml
=> ci: add release_to_dev cd

.github/workflows/release_to_dev.yaml, packages/mottai_flutter_app/dart-define.json, packages/mottai_flutter_app/ios/ExportOptions.plist, packages/mottai_flutter_app/ios/Flutter/Debug.xcconfig, packages/mottai_flutter_app/ios/Flutter/Release.xcconfig, packages/mottai_flutter_app/ios/Runner.xcodeproj/project.pbxproj, packages/mottai_flutter_app/ios/Runner/Info.plist
=> Release to dev

.github/workflows/release_to_dev.yaml, packages/mottai_flutter_app/ios/Flutter/Debug.xcconfig, packages/mottai_flutter_app/ios/Flutter/Release.xcconfig
=> fix: fix ios local debug build setting

.github/workflows/flutter_ci_test.yaml
=> chore: fix ci

.fvm/fvm_config.json, packages/dart_flutter_common/pubspec.lock, packages/firebase_common/pubspec.lock, packages/mottai_flutter_app/pubspec.lock
=> build: update flutter sdk version

.github/workflows/flutter_ci_test.yaml, packages/mottai_flutter_app/lib/auth/ui/button_builder.dart, packages/mottai_flutter_app/lib/chat/chat_room.dart, packages/mottai_flutter_app/lib/development/disable_user_account_request/ui/disable_user_account_request_controller.dart, packages/mottai_flutter_app/lib/development/firebase_storage/ui/firebase_storage.dart, packages/mottai_flutter_app/lib/host/ui/host_form.dart, packages/mottai_flutter_app/lib/map/ui/map.dart, packages/mottai_flutter_app/lib/pagination/firestore_pagination.dart, packages/mottai_flutter_app/lib/pagination/ui/pagination_list_view.dart, packages/mottai_flutter_app/lib/review/ui/reviews.dart, packages/mottai_flutter_app/lib/root/ui/root.dart, packages/mottai_flutter_app/lib/user/ui/user_mode.dart, packages/mottai_flutter_app/test/todo/ui/todos_test.dart
=> fix: fix firestore pagination bug

packages/firebase_common/lib/src/firestore_repositories/chat_message.dart, packages/mottai_flutter_app/lib/chat/chat_room.dart, packages/mottai_flutter_app/lib/chat/chat_rooms.dart, packages/mottai_flutter_app/lib/chat/ui/chat_room.dart
=> feat: refactor codes

packages/mottai_flutter_app/ios/Podfile, packages/mottai_flutter_app/ios/Podfile.lock, packages/mottai_flutter_app/ios/Runner.xcodeproj/project.pbxproj, packages/mottai_flutter_app/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
=> build: enable to build on iOS 17 by xcode 15
